#!/bin/bash

p=$1; shift
v=$1; shift
description=$1; shift
replaces=$1; shift

echo "Package: $p
Section: devel
Version: $v
Maintainer: Trygve Laugstøl <trygvis@inamo.no>
Architecture: all
Depends: default-jdk
Description: $description"

if [[ ! -z $replaces ]]
then
  echo "Replaces: $replaces"
fi

case "$p" in
  idea-ic)
    echo "Conflicts: idea-iu"
    ;;
  idea-iu)
    echo "Conflicts: idea-ic"
    ;;
esac
