#!/bin/bash

p=$1; shift
v=$1; shift
description=$1; shift
replaces=$1; shift

echo "Package: $p
Section: devel
Version: $v
Maintainer: Trygve Laugstøl <trygvis@inamo.no>
Architecture: all
Depends: java-sdk
Description: $description"

if [[ ! -z $replaces ]]
then
  echo "Replaces: $replaces"
fi

case "$p" in
  jetbrains-iic)
    echo "Conflicts: idea-iu, jetbrains-iiu"
    ;;
  jetbrains-iiu)
    echo "Conflicts: idea-ic, jetbrains-iic"
    ;;
esac
